### ISSUE TITLE
Source Maps

### ISSUE THREAD

**Issue by kenleezle** [pgilad/grunt-jade-usemin#29]
It would be nice if there was an easy way to enable source maps. I've added this to my gruntfile, which seems to be working. But it is surely boilerplate which would better serve most people as an option in jadeUsemin.

```
        cssmin: {
            options: {
                sourceMap: true
            }
        },
        concat: {
            options: {
                sourceMap: true,
                sourceMapName: function(dest) {
                    var fileName = dest.split('/').pop();
                    return '.tmp/' + fileName + '.map';
               }
            }
        },
        uglify: {
            options: {
                sourceMap: true,
                sourceMapIncludeSources: true,
                sourceMapIn: function(dest) {
                    var fileName = dest.split('/').pop();
                    return '.tmp/' + fileName + '.map';
                }
            }
        },
```

**Comment by pgilad** [comment]
Sounds like a great idea. You're welcome to submit a PR (with a test)

I would probably implement it somewhere around here:
https://github.com/pgilad/grunt-jade-usemin/blob/master/tasks/lib/jade_usemin.js#L101

And merge it into the config if user wants to use source-maps

**Comment by pgilad** [comment]
Hey @kenleezle a PR is very welcomed, in the meantime I'm closing this as it's kinda old now.
