### ISSUE TITLE
Warning: Task "concat:jadeUsemin-css" not found.

### ISSUE THREAD

**Issue by obibring** [pgilad/grunt-jade-usemin#31]
Hey, I can't get the task to work. Seeing this error:

```sh
Running "jadeUsemin:css" (jadeUsemin) task
Processing jade file src/cloud/views/public.jade
>> Finished with target block: public/stylesheets/app.css
Warning: Task "concat:jadeUsemin-css" not found. Use --force to continue.

Aborted due to warnings.
```

Here is my `jadeUsemin` grunt config:

```javascript
    jadeUsemin: {
      css: {
        files: [{
          src:  'src/cloud/views/public.jade',
          dest: 'clous/views/public.jade'
        }, {
          src:  'src/cloud/views/private.jade',
          dest: 'cloud/views/private.jade'
        }]
        options: {
          tasks: {
            css: ['concat', 'cssmin']
          }
          prefix: 'temp/public/"
        }
      }
    }
```

And my jade file:

```jade
    //-<!-- build:css public/stylesheets/app.css -->
    link(rel="stylesheet", href="stylesheets/test.css")
    link(rel="stylesheet", href="stylesheets/test2.css")
    //-<!-- endbuild -->
```

Am I doing something wrong?

**Comment by pgilad** [comment]
Hey, I can't see anything particularly wrong in your config...
Checkout the provided examples (https://github.com/pgilad/grunt-jade-usemin/blob/master/examples/examples.md) or the `Gruntfile.js` in this project for more examples.

Also try running your task with `grunt jadeUsemin:css --verbose --debug` for extra information.

Because we have a lot of tests here, I'm pretty sure it's a matter of your (mis)configuration. But maybe you've hit an edge case

**Comment by obibring** [comment]
It appears the plugin is attempting to run a grunt task named `jadeUsemin-css`. I'm assuming the plugin itself is supposed to register this task with `grunt`. A search through the source produces a single call to `grunt.registerTask()` to add the `"jadeUseminComplete"` task. Where is the `jadeUsemin-css` task supposed to be registered with `grunt`?

**Comment by pgilad** [comment]
This is the line that handles that: https://github.com/pgilad/grunt-jade-usemin/blob/d6901c73a6abf11cfe1cbac04b4d2794e5beae4a/tasks/lib/jade_usemin.js#L227

**Comment by obibring** [comment]
The issue is that my project does not directly load `grunt-contrib-concat` or `grunt-contrib-cssmin` directly. Since this plugin relies on these plugins having already been loaded, the `concat:` and `cssmin:` tasks fail. These dependencies should either be explicitly mentioned in the README, or even better, loaded by this task if necessary. Do you want me to have a look and issue a PR?

**Comment by pgilad** [comment]
Sure that'd be great :clap: but they are specified as `dependencies`:
https://github.com/pgilad/grunt-jade-usemin/blob/master/package.json#L30-L36

**Comment by pgilad** [comment]
hey @obibring is this still relevant?

**Comment by obibring** [comment]
I'm assuming that yes, the issue still exists. But I haven't had a chance to work on a PR yet :-/

**Comment by pgilad** [comment]
It's kind of weird, because those items are listed as dependencies of `grunt-jade-usemin`.

Can you try re-installing latest version again?

**Comment by pgilad** [comment]
Closing this. Please re-open if you used latest version and it's still happening.

**Comment by davidleureka** [comment]
Can we re-open this? It appears to still be a problem. I followed the example given here

https://github.com/pgilad/grunt-jade-usemin/blob/master/examples/examples.md#basic-javascript-pattern

and I get the message:
Warning: Task "concat:jadeUsemin-js" not found. Use --force to continue.

If I manually add grunt-contrib-concat and grunt-contrib-uglify through npm and reference them in the grunt file then things work fine. I can see that grunt-jade-usemin does in fact download grunt-contrib-concat and grunt-contrib-uglify. They exist in its node_modules directory. Not sure why it doesn't see them.

Similar things happen with css as initially noted.

And as I minor note, the example referenced above gives

files: [{
    dest: './src/partials/sample.jade',
    src: './public/partials/sample.jade'
}]

which appears to mix up src and dest.

**Comment by pgilad** [comment]
Perhaps this is due to lack of `grunt.loadNpmTasks`. Do you use something like `load-grunt-plugins` in your gruntfile or do you load them manually?

I'm thinking when you install `grunt-contrib-concat` manually it is saved in your package.json and thus gets loaded with `load-grunt-plugins`

**Comment by davidleureka** [comment]
I'm not using `load-grunt-tasks` and I don't have `grunt-contrib-concat` manually installed. Do I need to manually install all the dependencies of `grunt-jade-usemin'?

`grunt-jade-usemin` has the following packages in its own `node_modules` directory:

    grunt-contrib-concat
    grunt-contrib-cssmin
    grunt-contrib-uglify
    lodash
    slash

Is it just not finding them? Or do I have some fundamental misunderstanding about how grunt and npm work?

Here is `package.json`:

    {
        "name": "test",
        "description": "test",
        "engines": {
          "node": "5.1.1",
          "npm": "3.4.1"
        },
        "version": "0.0.1",
        "private": true,
        "dependencies": {
            "grunt": "0.4.5",
            "grunt-jade-usemin": "1.1.0"
        }
    }


Here is `gruntfile.js`:

    module.exports = function(grunt) {
        grunt.initConfig({
            pkg: grunt.file.readJSON('package.json'),
            jadeUsemin: {
                scripts: {
                    options: {
                        tasks: {
                            js: ['concat', 'uglify']
                        }
                    },
                    files: [{
                        dest: './src/partials/sample.jade',
                        src: './public/partials/sample.jade'
                    }]
                }
            }
        });
        grunt.loadNpmTasks('grunt-jade-usemin');
        grunt.registerTask('default', ['jadeUsemin']);
    };

**Comment by davidleureka** [comment]
Any updates on this?

**Comment by pgilad** [comment]
Yeah I get the problem. I need to add `grunt.loadNpmTasks('grunt-contrib-concat')` manually into the lib..

**Comment by pgilad** [comment]
Hopefully fixed by https://github.com/pgilad/grunt-jade-usemin/commit/ba8a93fd0a4113a9cc86a9a1d8ce4ea1c3cf05df

Please use latest (1.2.0) version
