### ISSUE TITLE
Should we fail when script src does not exist?

### ISSUE THREAD

**Issue by igrcic** [pgilad/grunt-jade-usemin#32]
If some script is not found now the usemin task doesn't fail. 
This doesn't play very nice with CI logic, because we dont notice the error right away.

Shouldn't we do grunt.fail or grunt.log.error for this?

grunt.log.warn("Found script src that doesn't exist: " + src);

**Comment by pgilad** [comment]
Yes I definitely agree it should fail. You're welcome to add a PR request!

**Comment by pgilad** [comment]
Added an option `failOnMissingSource` which will fail the task if a source file is missing. Otherwise only a warning is raised.

Thanks for the tip!
