### ISSUE TITLE
Pug files are not processed

### ISSUE THREAD

**Issue by gurucomkz** [pgilad/grunt-jade-usemin#33]
I wanted to process .pug files with grunt-jade-usemin but could not without patching it.
Would you consider allowing *.pug files to be processed by this plugin?

I wrote a patch to fix this issue.
[patch-allow-pug.txt](https://github.com/pgilad/grunt-jade-usemin/files/491772/patch-allow-pug.txt)

**Comment by pgilad** [comment]
Definitely! PR welcomed

**Comment by pgilad** [comment]
closed via https://github.com/pgilad/grunt-jade-usemin/commit/3471bb74fc413015266460b2d469eb1ce4f8fce0
