### ISSUE TITLE
possibly wrong warning on css&js build types

### ISSUE THREAD

**Issue by gurucomkz** [pgilad/grunt-jade-usemin#35]
I see that file `tasks/lib/jade_usemin.js` complains about lines like 
`//-<!-- build:css /styles/bundle.min.css -->`
`//-<!-- build:js /scripts/bundle.min.js -->`

But plugin continues to work and does what it is supposed to do well.

> Running "jadeUsemin:main" (jadeUsemin) task
> Processing jade file ./.tmp/views/partials/scripts.pug
>  `>``>` Unsupported build type: js
>  `>``>` Finished with target block: .tmp/scripts/bundle.min.js
> Processing jade file ./.tmp/views/partials/styles.pug
>  `>``>` Unsupported build type: css
>  `>``>` Finished with target block: .tmp/styles/bundle.min.css
> 

Code that produce warning `tasks/lib/jade_usemin.js:317:`
```javascript
if (includes(['css', 'js'], type)) {
    grunt.log.warn('Unsupported build type: ' + type);
}
```

Maybe negations is missing before `includes` call? I assume that css and js build types are the **only** ones supported, right?

**Comment by pgilad** [comment]
Yeah, it's a mistake 🎅

**Comment by pgilad** [comment]
Fixed thanks!

**Comment by gurucomkz** [comment]
Thank you!!!!
